### ISSUE TITLE
Question for failed of step ktlintMainSourceSetCheck 

### ISSUE THREAD

**Issue by seungdols** [JLLeitschuh/ktlint-gradle#340]
Hi, 

Thank you for make by good lint tool.

I will plan for using kotlin in production code, I have some issue. 

I need to lint tool for kotlin code. So, I decided this tool use.

It's use and then build failed. 

It's failed ktlintMainSourceSetCheck in build step.

* Kotlin version: 1.3.50
* Ktlint version: 9.2.1
* Java version: 1.8.222 (openjdk)

```
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.ClassCastException: org.jetbrains.kotlin.com.intellij.psi.impl.file.PsiLargeTextFileImpl cannot be cast to org.jetbrains.kotlin.psi.KtFile
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.pinterest.ktlint.KtlintCommandLine.parallel(Main.kt:531)
	at com.pinterest.ktlint.KtlintCommandLine.parallel$default(Main.kt:505)
	at com.pinterest.ktlint.KtlintCommandLine.lintFiles(Main.kt:264)
	at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:232)
	at com.pinterest.ktlint.Main.main(Main.kt:61)
Caused by: java.lang.ClassCastException: org.jetbrains.kotlin.com.intellij.psi.impl.file.PsiLargeTextFileImpl cannot be cast to org.jetbrains.kotlin.psi.KtFile
	at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:137)
	at com.pinterest.ktlint.internal.FileUtilsKt.lintFile(FileUtils.kt:51)
	at com.pinterest.ktlint.KtlintCommandLine.process(Main.kt:357)
	at com.pinterest.ktlint.KtlintCommandLine.access$process(Main.kt:115)
	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$2$1.call(Main.kt:256)
	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$2$1.call(Main.kt:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

> Task :apps:api:ktlintMainSourceSetCheck FAILED
```

Why cause this situation?

You need to help me.

Thank you.

**Comment by JLLeitschuh** [comment]
What version of the plugin are you using? Any chance you captured a build scan? Is this reproducible?

**Comment by seungdols** [comment]
My plugin version is here. 

```
plugins {
    id 'war'
    id 'groovy'
    id 'org.jetbrains.kotlin.jvm' version '1.3.50'
    id 'org.jetbrains.kotlin.kapt' version "1.3.50"
    id 'org.jetbrains.kotlin.plugin.spring' version "1.3.50"
    id 'org.jlleitschuh.gradle.ktlint' version '9.2.1'
}
```

No, I haven't ever used a build scan. 

So, I try "build scan", It's a success. 

This issue causes build failure of Jenkins(CI). Maybe Jenkins contains some issues. 

Are you know this issue in Jenkins? 

It’s reproducible in Jenkins. It’s the same reason.

Are you help me?

Thank you for your kindness.

**Comment by Tapchicoma** [comment]
I think this is the issue of "ktlint" rather then this plugin. Could you open [a new issue](https://github.com/pinterest/ktlint/issues/new) in ktlint repository?

**Comment by seungdols** [comment]
@Tapchicoma Wow, Thank you so much. Ok. I will open new issue in ktlint repository.

**Comment by Tapchicoma** [comment]
@seungdols I've reopening this issue as more appropriate place to discuss why in your setup `ktlint-gradle` with default settings tries to check `xml` and `war` files.

Would be really awesome if you could provide minimal reproducible project. And as you told that it is only happening on Jenkins CI - do you have any differences how you run your builds on CI?

**Comment by Tapchicoma** [comment]
Theoretically tasks should only take `.kt` or `.kts` files based on this line: https://github.com/JLLeitschuh/ktlint-gradle/blob/cac79c462a90e5806352907fd80d08ed4ecb13dd/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/BaseKtlintCheckTask.kt#L126

Could it be that you try to configure `SourceTask` in your project setup?

**Comment by seungdols** [comment]
@Tapchicoma Jenkins CI build command and locally build command is same. Can you guide `SourceTask` to me? 🙏🏼

**Comment by Tapchicoma** [comment]
Ktlint tasks extends Gradle [SourceTask](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/SourceTask.html). This task implements [PatternFilterable](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/util/PatternFilterable.html) interface that allows to either include or exclude some files based on some pattern.

Ktlint tasks by default include all "*.kt" and "*.kts" files, tough it is still possible externally override it.

**Comment by Tapchicoma** [comment]
@seungdols have you had a chance to check your build scripts to see if they configure somehow `SourceTask` when running on CI?

**Comment by seungdols** [comment]
@JLLeitschuh I'm so Sorry. I'm late. I will try to Gradle SourceTask next week. Because of the corona virus 😭, I was busy and could not check it. I will check and inform you next week.

**Comment by Tapchicoma** [comment]
@seungdols take care of yourself, it is not urgent.

**Comment by seungdols** [comment]
@Tapchicoma So sorry. i'm late reply.

I try to addtion ktlint configure in my project. 

this options add in build.gradle. 

```groovy
ktlint {
    debug = true
    verbose = true
    android = false
    outputToConsole = true
    outputColorName = "RED"
    ignoreFailures = true
    enableExperimentalRules = true
    filter {
        include("**/*.kt")
    }
}
```

So, jenkins CI is success. But I saw error message. 

```text
Exception in thread "main" java.util.concurrent.ExecutionException: java.lang.ClassCastException: org.jetbrains.kotlin.com.intellij.psi.impl.file.PsiLargeTextFileImpl cannot be cast to org.jetbrains.kotlin.psi.KtFile
	at java.util.concurrent.FutureTask.report(FutureTask.java:122)
	at java.util.concurrent.FutureTask.get(FutureTask.java:192)
	at com.pinterest.ktlint.KtlintCommandLine.parallel(Main.kt:531)
	at com.pinterest.ktlint.KtlintCommandLine.parallel$default(Main.kt:505)
	at com.pinterest.ktlint.KtlintCommandLine.lintFiles(Main.kt:264)
	at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:232)
	at com.pinterest.ktlint.Main.main(Main.kt:61)
Caused by: java.lang.ClassCastException: org.jetbrains.kotlin.com.intellij.psi.impl.file.PsiLargeTextFileImpl cannot be cast to org.jetbrains.kotlin.psi.KtFile
	at com.pinterest.ktlint.core.KtLint.lint(KtLint.kt:137)
	at com.pinterest.ktlint.internal.FileUtilsKt.lintFile(FileUtils.kt:51)
	at com.pinterest.ktlint.KtlintCommandLine.process(Main.kt:357)
	at com.pinterest.ktlint.KtlintCommandLine.access$process(Main.kt:115)
	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$2$1.call(Main.kt:256)
	at com.pinterest.ktlint.KtlintCommandLine$lintFiles$2$1.call(Main.kt:115)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)

```

in result, lint plugin is usable. Thank you.

**Comment by Tapchicoma** [comment]
`ignoreFailures = true` - this will always succeed the build.

Which Gradle log level are you using on Jenkins CI? Standard one or info?

If you could create small reproducible project - would be really helpful.

**Comment by Tapchicoma** [comment]
Feel free to open a new issue if this problem still exists (especially after next `10.0.0` release).
