### ISSUE TITLE
Tasks fail when project path contains space on Windows

### ISSUE THREAD

**Issue by connyduck** [JLLeitschuh/ktlint-gradle#362]
```
> Task :ktlintKotlinScriptCheck FAILED
1 actionable task: 1 executed
Exception in thread "main" java.io.FileNotFoundException: C:\Users\Conny (Access is denied)
	at java.io.FileOutputStream.open0(Native Method)
	at java.io.FileOutputStream.open(FileOutputStream.java:270)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
	at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
	at java.io.PrintStream.<init>(PrintStream.java:248)
	at com.pinterest.ktlint.KtlintCommandLine.toReporter(Main.kt:414)
	at com.pinterest.ktlint.KtlintCommandLine.loadReporter(Main.kt:392)
	at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:222)
	at com.pinterest.ktlint.Main.main(Main.kt:61)
```

The full path to the project would be `C:\Users\Conny Duck\Android\projectname` but seems like the space is not handled correctly. I am using version `9.2.1`.

**Comment by JLLeitschuh** [comment]
That sounds like it's a bug in Ktlint proper not this plugin. @Tapchicoma do you agree?

**Comment by Tapchicoma** [comment]
could be a plugin issue as well, need some check.

@connyduck could you drop here ktlint args generated file? Usually it is located in `build/ktlint/*.args`

**Comment by connyduck** [comment]
Here you go

`ktlintKotlinScriptCheck.args`

```
--reporter=plain
--color
--reporter=plain,output=C:\Users\Conny Duck\Android\projectname\build\reports\ktlint\ktlintKotlinScriptCheck.txt
build.gradle.kts
settings.gradle.kts
```

**Comment by Tapchicoma** [comment]
Looking at reporter line, I think plugin forgot to escape spaces in path, so most probably it is not just Windows specific issue.

**Comment by FrankHossfeld** [comment]
This problem also exists on macOS:

```
> Task :buildSrc:ktlintKotlinScriptCheck FAILED
Exception in thread "main" java.io.FileNotFoundException: /Volumes/El (Operation not permitted)
    at java.io.FileOutputStream.open0(Native Method)
    at java.io.FileOutputStream.open(FileOutputStream.java:270)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:213)
    at java.io.FileOutputStream.<init>(FileOutputStream.java:101)
    at java.io.PrintStream.<init>(PrintStream.java:248)
    at com.pinterest.ktlint.KtlintCommandLine.toReporter(Main.kt:414)
    at com.pinterest.ktlint.KtlintCommandLine.loadReporter(Main.kt:392)
    at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:222)
    at com.pinterest.ktlint.Main.main(Main.kt:61)
```
