### ISSUE TITLE
Support Kotlin 1.4

### ISSUE THREAD

**Issue by eiswind** [JLLeitschuh/ktlint-gradle#381]
1.4 has the new 
```
fun interface {
}
```
syntax for sam types. ktlint is already updating this
https://github.com/pinterest/ktlint/issues/726

**Comment by JLLeitschuh** [comment]
Can you just specify a fixed/released version of ktlint with the `version` argument to use it?

**Comment by JLLeitschuh** [comment]
If you're seeing some specific exception when trying to process Kotlin 1.4 code that comes from this plugin, not from ktlint itself, then please provide a stack trace.

**Comment by maffelbaffel** [comment]
I'm getting the following stacktrace:
```
Exception in thread "main" java.lang.NoSuchFieldError: FUN_KEYWORD
	at com.pinterest.ktlint.core.ast.ElementType.<clinit>(ElementType.kt:154)
	at com.pinterest.ktlint.ruleset.standard.ChainWrappingRule.<init>(ChainWrappingRule.kt:36)
	at com.pinterest.ktlint.ruleset.standard.StandardRuleSetProvider.get(StandardRuleSetProvider.kt:11)
	at com.pinterest.ktlint.KtlintCommandLine.loadRulesets(Main.kt:546)
	at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:222)
	at com.pinterest.ktlint.Main.main(Main.kt:62)
```
There is already a bug filed [here](https://github.com/pinterest/ktlint/issues/830).

**Comment by JLLeitschuh** [comment]
This stack trace is purely in ktlint, not this plugin. If there are still issues after an official Ktlint release is published, please leave a comment and I'll reopen this issue.
