### ISSUE TITLE
Managing ktLint version via refreshVersions

### ISSUE THREAD

**Issue by realdadfish** [JLLeitschuh/ktlint-gradle#382]
I'm using the excellent https://github.com/jmfayard/refreshVersions Gradle plugin to manage all build-time and run-time dependencies of my app. This works well with a variety of Gradle plugins as well where specific external tool dependencies need to be set (e.g. Jacoco or PMD CPD), however, specifying the plugin's placeholder version "_" like so:

```kotlin
configure<KtlintExtension> {
    version.set("_")
}
```

makes the plugin error out with this exception:

```
java.lang.IllegalArgumentException: Invalid version string [_]
        at org.jlleitschuh.gradle.shadow.net.swiftzer.semver.SemVer$Companion.parse(SemVer.kt:28)
        at org.jlleitschuh.gradle.ktlint.ConfigurationsKt.resolveGroup(Configurations.kt:36)
        at org.jlleitschuh.gradle.ktlint.ConfigurationsKt.access$resolveGroup(Configurations.kt:1)
        at org.jlleitschuh.gradle.ktlint.ConfigurationsKt$createKtlintConfiguration$$inlined$apply$lambda$1.call(Configurations.kt:26)
        at org.jlleitschuh.gradle.ktlint.ConfigurationsKt$createKtlintConfiguration$$inlined$apply$lambda$1.call(Configurations.kt)
        at org.gradle.api.internal.provider.DefaultProvider.calculateOwnValue(DefaultProvider.java:66)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.Collectors$ElementFromProvider.collectEntries(Collectors.java:98)
        at org.gradle.api.internal.provider.Collectors$TypedCollector.collectEntries(Collectors.java:329)
        at org.gradle.api.internal.provider.Collectors$TypedCollector.collectInto(Collectors.java:324)
        at org.gradle.api.internal.collections.AbstractIterationOrderRetainingElementSource$Element.realize(AbstractIterationOrderRetainingElementSource.java:316)
        at org.gradle.api.internal.collections.AbstractIterationOrderRetainingElementSource.realizePending(AbstractIterationOrderRetainingElementSource.java:141)
        at org.gradle.api.internal.DefaultDomainObjectCollection.addEagerAction(DefaultDomainObjectCollection.java:226)
        at org.gradle.api.internal.DefaultDomainObjectCollection.all(DefaultDomainObjectCollection.java:144)
        at org.gradle.api.internal.CompositeDomainObjectSet.addCollection(CompositeDomainObjectSet.java:110)
        at org.gradle.api.internal.CompositeDomainObjectSet.create(CompositeDomainObjectSet.java:58)
        at org.gradle.api.internal.collections.DefaultDomainObjectCollectionFactory.newDomainObjectSet(DefaultDomainObjectCollectionFactory.java:111)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.initAllDependencies(DefaultConfiguration.java:785)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration.getAllDependencies(DefaultConfiguration.java:775)
        at org.gradle.api.internal.artifacts.configurations.DefaultConfiguration_Decorated.getAllDependencies(Unknown Source)
        at org.gradle.api.internal.artifacts.ivyservice.ShortCircuitEmptyConfigurationResolver.resolveBuildDependencies(ShortCircuitEmptyConfigurationResolver.java:73)
        at org.gradle.api.internal.artifacts.ivyservice.ErrorHandlingConfigurationResolver.resolveBuildDependencies(ErrorHandlingConfigurationResolver.java:63)
        ... 119 more
```

Now it's not a big issue to make the exception and specify the KtLint version to use inline, but it would be nonetheless great if the two plugins would kind of work together :)

**Comment by JLLeitschuh** [comment]
We use the version you provide to do a bunch of checks to verify the other configurations you are making are compatible with the ktlint version. The only way that we could support this use case and also support what you want would be to resolve the dependency and see what version we actually get and then use that. Not saying that's out of the question, but it's different from the way we've thought about this before. Are you willing to provide a PR to add support for this behaviour?

You need to ensure that the evaluation of the dependencies version is still lazy.

@Tapchicoma do you think this is possible given how our codebase works currently?

**Comment by realdadfish** [comment]
Hrm... haven't tried this, but out of my head, what if one would try to change the group name after the fact, like so?

```kotlin
configuration.resolutionStrategy.eachDependency {
  if (requested.group == "com.pinterest" && requested.name == "ktlint" && SemVer.parse(requested.version) < SemVer(0, 32, 0)) {
    useTarget("com.github.shyiko:ktlint:${requested.version}")
  }
}
```

**Comment by realdadfish** [comment]
And I haven't overseen where else the version is used to distinguish things; if this actually complicates matters a lot in your plugin, I'd probably rather not do it.

**Comment by JLLeitschuh** [comment]
You may want to take a larger look at how many places we use the `SemVer` parser, we use it for quite a few things.

**Comment by realdadfish** [comment]
Hrm... ok, not worth the effort. Thanks for your time!
