### ISSUE TITLE
Upgrading from 9.3.0 to 9.4.0: ktlintCheck fails cause of java.lang.NoSuchFieldError: FUN_KEYWORD

### ISSUE THREAD

**Issue by theexiile1305** [JLLeitschuh/ktlint-gradle#396]
With the upgrade to version `9.4.0` the following exception is thrown with the stacktrace when executing the Gradle Task `ktlintCheck`:
```
Task :ktlintTestSourceSetCheck FAILED
Exception in thread "main" java.lang.NoSuchFieldError: FUN_KEYWORD
	at com.pinterest.ktlint.core.ast.ElementType.<clinit>(ElementType.kt:154)
	at com.pinterest.ktlint.ruleset.experimental.SpacingAroundAngleBracketsRule.<clinit>(SpacingAroundAngleBracketsRule.kt:94)
	at com.pinterest.ktlint.ruleset.experimental.ExperimentalRuleSetProvider.get(ExperimentalRuleSetProvider.kt:18)
	at com.pinterest.ktlint.KtlintCommandLine.loadRulesets(Main.kt:550)
	at com.pinterest.ktlint.KtlintCommandLine.run(Main.kt:222)
	at com.pinterest.ktlint.Main.main(Main.kt:62)
```

My Environment:
- macOS Catalina Version 10.15.6
- Java: openjdk version "14.0.2" 2020-07-14
- Gradle: 6.1.1
- IntelliJ IDEA 2020.2 (Ultimate Edition) Build #IU-202.6397.94, built on July 27, 2020

This issue occurs within IntelliJ and command line usage.

**Comment by Tapchicoma** [comment]
Please check last question in faq: https://github.com/JLLeitschuh/ktlint-gradle#faq

**Comment by theexiile1305** [comment]
Sorry @Tapchicoma, but the approach describe in your FAQ doesn't work for me. I've added the configuration in my `build.gradle.kts` file like the following: 
```
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "2.3.3.RELEASE"
	id("io.spring.dependency-management") version "1.0.10.RELEASE"
	idea
	war
	kotlin("jvm") version "1.3.61"
	kotlin("plugin.spring") version "1.3.61"
	kotlin("plugin.jpa") version "1.3.61"
	kotlin("plugin.allopen") version "1.3.61"
	kotlin("kapt") version "1.3.72"
	id("io.gitlab.arturbosch.detekt") version "1.13.0"
	id("org.jlleitschuh.gradle.ktlint") version "9.4.0"
}

configurations.all {
	if(!name.startsWith("ktlint")) {
		resolutionStrategy {
			eachDependency {
				// Force Kotlin to our version
				if (requested.group == "org.jetbrains.kotlin") {
					useVersion("1.3.72")
				}
			}
		}
	}
}

group = "com.github.theexiile1305"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_11

springBoot {
	buildInfo()
}

repositories {
	jcenter()
}

dependencies {
	implementation("io.springfox:springfox-boot-starter:3.0.0")

	implementation("org.springframework.boot:spring-boot-starter-data-jpa")
	implementation("org.springframework.boot:spring-boot-starter-actuator")
	implementation("org.springframework.boot:spring-boot-starter-web")
	implementation("org.springframework.boot:spring-boot-starter-mail")
	implementation("org.springframework.boot:spring-boot-starter-freemarker")
	implementation("org.springframework.boot:spring-boot-starter-security")
	implementation("org.springframework.boot:spring-boot-starter-validation")
	implementation("org.keycloak:keycloak-spring-security-adapter:11.0.2")

	implementation("com.github.doyaaaaaken:kotlin-csv-jvm:0.11.0")

	implementation("no.api.freemarker:freemarker-java8:2.0.0")

	implementation("com.vladmihalcea:hibernate-types-52:2.9.13")
	implementation("org.postgresql:postgresql")
	implementation("org.flywaydb:flyway-core")

	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")

	implementation("com.fasterxml.jackson.module:jackson-module-kotlin:2.11.2")
	implementation("com.fasterxml.jackson.dataformat:jackson-dataformat-xml:2.11.2")
	implementation("com.fasterxml.jackson.core:jackson-databind:2.11.2")

	implementation("com.migesok:jaxb-java-time-adapters:1.1.3")

	implementation("org.hibernate:hibernate-jcache:5.4.21.Final")
	implementation("org.ehcache:ehcache:3.9.0")

	kapt("org.hibernate:hibernate-jpamodelgen:5.4.21.Final")

	developmentOnly("org.springframework.boot:spring-boot-devtools")
	providedRuntime("org.springframework.boot:spring-boot-starter-tomcat")

	testImplementation("org.springframework.boot:spring-boot-starter-test") {
		exclude(group = "org.junit.vintage", module = "junit-vintage-engine")
		exclude(module = "junit")
		exclude(module = "mockito-core")
	}
	testImplementation("org.springframework.security:spring-security-test")
	testImplementation("com.ninja-squad:springmockk:2.0.3")
	testImplementation("org.jeasy:easy-random-core:4.2.0")
}

allOpen {
	annotation("javax.persistence.Entity")
	annotation("javax.persistence.Embeddable")
	annotation("javax.persistence.MappedSuperclass")
}

tasks.processResources {
	filesMatching("application.yml") {
		expand(project.properties)
	}
}

tasks.bootWar {
	setProperty("archiveFileName", "service.war")
}

tasks.withType<Test> {
	useJUnitPlatform()
	systemProperties["spring.profiles.active"] = project.properties["spring.profile"]

	addTestListener(object : TestListener {
		override fun beforeSuite(suite: TestDescriptor) {}
		override fun beforeTest(testDescriptor: TestDescriptor) {
			logger.lifecycle("Running test: $testDescriptor")
		}

		override fun afterTest(testDescriptor: TestDescriptor, result: TestResult) {}
		override fun afterSuite(suite: TestDescriptor, result: TestResult) {
			if (suite.parent == null) { // root suite
				logger.lifecycle("----")
				logger.lifecycle("Test result: ${result.resultType}")
				logger.lifecycle("Test summary: ${result.testCount} tests, " +
						"${result.successfulTestCount} succeeded, " +
						"${result.failedTestCount} failed, " +
						"${result.skippedTestCount} skipped")
			}
		}
	})
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict", "-Xinline-classes")
		jvmTarget = "11"
	}
}
```

Can you please help me out?

**Comment by Tapchicoma** [comment]
I see you are still defining Kotlin `1.3.61` in dependencies so version enforcement configuration in your case will look following:
```gradle
configurations.all {
	if(!name.startsWith("ktlint")) {
		resolutionStrategy {
			eachDependency {
				// Force Kotlin to our version
				if (requested.group == "org.jetbrains.kotlin") {
					useVersion("1.3.61")
				}
			}
		}
	}
}
```

Are you sure that you don't have in some other build script Kotlin version enforcement? Main case of this problem is when Ktlint 0.38+ uses Kotlin <1.3.72 versions.

**Comment by theexiile1305** [comment]
@Tapchicoma Thx for that quick response. I don't have any other build scripts or version enforcement in such files. I've adjusted the above `build.gradle.kts` file and the configurations looks like your reply. Unfortunately, I run into the same exception.

**Comment by Tapchicoma** [comment]
In your case it is `id("io.spring.dependency-management") version "1.0.10.RELEASE"` plugin the forces lower kotlin dependency for `ktlint` configuration. Commenting this plusing allows ktlint to run normally.

You could check which kotlin version is used via `./gradlew dependencies --configuration ktlint`.

Unfortunately I am not familiar with spring dependency-management plugin to help you with ktlint configuration exclusion.

**Comment by theexiile1305** [comment]
@Tapchicoma Thank you very much, upgrading all kotlin related stuff to version `1.4.10` solves the problem automatically.
