### ISSUE TITLE
ktlint check fails on Android project

### ISSUE THREAD

**Issue by SergeyShustikov** [JLLeitschuh/ktlint-gradle#397]
I'm trying to launch ktlint and it fails

```8:44:55: Executing task 'ktlintCheck --stacktrace'...

> Configure project :sm_main
OneSignal Warning: Could not get AGP plugin version

FAILURE: Build failed with an exception.

* What went wrong:
org.jlleitschuh.gradle.ktlint.KtlintCheckTask.newOutputFile()Lorg/gradle/api/file/RegularFileProperty;

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoSuchMethodError: org.jlleitschuh.gradle.ktlint.KtlintCheckTask.newOutputFile()Lorg/gradle/api/file/RegularFileProperty;
	at org.jlleitschuh.gradle.ktlint.KtlintCheckTask.getEnabledReports$ktlint_gradle(KtlintCheckTask.kt:70)
	at org.jlleitschuh.gradle.ktlint.KtlintCheckTask.getReportOutputFiles(KtlintCheckTask.kt:156)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1$1.create(AbstractNestedRuntimeBeanNode.java:77)
	at org.gradle.internal.deprecation.DeprecationLogger.whileDisabled(DeprecationLogger.java:228)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue$1.get(AbstractNestedRuntimeBeanNode.java:73)
	at com.google.common.base.Suppliers$NonSerializableMemoizingSupplier.get(Suppliers.java:167)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode$BeanPropertyValue.getUnprocessedValue(AbstractNestedRuntimeBeanNode.java:146)
	at org.gradle.api.internal.tasks.properties.FileParameterUtils.resolveOutputFilePropertySpecs(FileParameterUtils.java:110)
	at org.gradle.execution.plan.LocalTaskNode$1.lambda$visitOutputFileProperty$1(LocalTaskNode.java:206)
	at org.gradle.execution.plan.LocalTaskNode.withDeadlockHandling(LocalTaskNode.java:289)
	at org.gradle.execution.plan.LocalTaskNode.access$000(LocalTaskNode.java:51)
	at org.gradle.execution.plan.LocalTaskNode$1.visitOutputFileProperty(LocalTaskNode.java:202)
	at org.gradle.api.internal.tasks.properties.annotations.AbstractOutputPropertyAnnotationHandler.visitPropertyValue(AbstractOutputPropertyAnnotationHandler.java:50)
	at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode.visitProperties(AbstractNestedRuntimeBeanNode.java:56)
	at org.gradle.api.internal.tasks.properties.bean.RootRuntimeBeanNode.visitNode(RootRuntimeBeanNode.java:32)
	at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker.visitProperties(DefaultPropertyWalker.java:41)
	at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:44)
	at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:34)
	at org.gradle.execution.plan.LocalTaskNode.resolveMutations(LocalTaskNode.java:199)
	at org.gradle.execution.plan.DefaultExecutionPlan.getResolvedMutationInfo(DefaultExecutionPlan.java:604)
	at org.gradle.execution.plan.DefaultExecutionPlan.selectNext(DefaultExecutionPlan.java:532)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$executeNextNode$1(DefaultPlanExecutor.java:166)
	at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:155)
	at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
	at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
	at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
	at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)


* Get more help at https://help.gradle.org

BUILD FAILED in 1s```

**Comment by Tapchicoma** [comment]
What Gradle version are you using?

**Comment by Tapchicoma** [comment]
Closing it, feel free to open a new issue if it is still the case for you.
