### ISSUE TITLE
Version 10.0.0 fails in non-Kotlin projects

### ISSUE THREAD

**Issue by DanySK** [JLLeitschuh/ktlint-gradle#443]
Hi,
I use Ktlint on Gradle projects even when I do not use Kotlin as a language, in order to check the Gradle build files.
Upgrades to version 10.0.0 of the plugin, however, fails:

```
❯ ./gradlew check --stacktrace
Picked up _JAVA_OPTIONS: -Dawt.useSystemAAFontSettings=on

> Configure project :
No username configured for MavenCentral at https://oss.sonatype.org/service/local/staging/deploy/maven2/.

FAILURE: Build failed with an exception.

* What went wrong:
org/jetbrains/kotlin/konan/file/File

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
java.lang.NoClassDefFoundError: org/jetbrains/kotlin/konan/file/File
        at org.jlleitschuh.gradle.ktlint.tasks.GenerateReportsTask$reportsOutputDirectory$1.transform(GenerateReportsTask.kt:100)
        at org.jlleitschuh.gradle.ktlint.tasks.GenerateReportsTask$reportsOutputDirectory$1.transform(GenerateReportsTask.kt:35)
        at org.gradle.api.internal.provider.FlatMapProvider.doMapValue(FlatMapProvider.java:54)
        at org.gradle.api.internal.provider.FlatMapProvider.calculateOwnValue(FlatMapProvider.java:50)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.MappingProvider.calculateOwnValue(MappingProvider.java:55)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.calculateValue(AbstractMinimalProvider.java:103)
        at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:128)
        at org.gradle.api.internal.provider.DefaultProperty.calculateValueFrom(DefaultProperty.java:25)
        at org.gradle.api.internal.provider.AbstractProperty.doCalculateValue(AbstractProperty.java:133)
        at org.gradle.api.internal.provider.AbstractProperty.calculateOwnValueNoProducer(AbstractProperty.java:121)
        at org.gradle.api.internal.file.DefaultFilePropertyFactory$AbstractFileVar.access$100(DefaultFilePropertyFactory.java:180)
        at org.gradle.api.internal.file.DefaultFilePropertyFactory$AbstractFileVar$2.calculateOwnValue(DefaultFilePropertyFactory.java:263)
        at org.gradle.api.internal.provider.AbstractMinimalProvider.getOrNull(AbstractMinimalProvider.java:93)
        at org.gradle.api.internal.tasks.properties.FileParameterUtils.resolveOutputFilePropertySpecs(FileParameterUtils.java:116)
        at org.gradle.execution.plan.LocalTaskNode$1.lambda$visitOutputFileProperty$1(LocalTaskNode.java:201)
        at org.gradle.execution.plan.LocalTaskNode.withDeadlockHandling(LocalTaskNode.java:267)
        at org.gradle.execution.plan.LocalTaskNode.access$000(LocalTaskNode.java:48)
        at org.gradle.execution.plan.LocalTaskNode$1.visitOutputFileProperty(LocalTaskNode.java:197)
        at org.gradle.api.internal.tasks.properties.annotations.AbstractOutputPropertyAnnotationHandler.visitPropertyValue(AbstractOutputPropertyAnnotationHandler.java:50)
        at org.gradle.api.internal.tasks.properties.bean.AbstractNestedRuntimeBeanNode.visitProperties(AbstractNestedRuntimeBeanNode.java:56)
        at org.gradle.api.internal.tasks.properties.bean.RootRuntimeBeanNode.visitNode(RootRuntimeBeanNode.java:32)
        at org.gradle.api.internal.tasks.properties.DefaultPropertyWalker.visitProperties(DefaultPropertyWalker.java:41)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:44)
        at org.gradle.api.internal.tasks.TaskPropertyUtils.visitProperties(TaskPropertyUtils.java:34)
        at org.gradle.execution.plan.LocalTaskNode.resolveMutations(LocalTaskNode.java:194)
        at org.gradle.execution.plan.DefaultExecutionPlan.getResolvedMutationInfo(DefaultExecutionPlan.java:626)
        at org.gradle.execution.plan.DefaultExecutionPlan.selectNext(DefaultExecutionPlan.java:554)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.lambda$executeNextNode$1(DefaultPlanExecutor.java:166)
        at org.gradle.internal.resources.DefaultResourceLockCoordinationService.withStateLock(DefaultResourceLockCoordinationService.java:45)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.executeNextNode(DefaultPlanExecutor.java:155)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:124)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:64)
        at org.gradle.internal.concurrent.ManagedExecutorImpl$1.run(ManagedExecutorImpl.java:48)
        at org.gradle.internal.concurrent.ThreadFactoryImpl$ManagedThreadRunnable.run(ThreadFactoryImpl.java:56)


* Get more help at https://help.gradle.org

BUILD FAILED in 680ms
7 actionable tasks: 7 up-to-date
```

This looks like a missing dependency plugin-side

**Comment by Tapchicoma** [comment]
Could it happen that your project are using one of deprecated Kotlin Gradle plugins support for which was removed: https://github.com/JLLeitschuh/ktlint-gradle/blob/master/CHANGELOG.md#changed-1?

**Comment by DanySK** [comment]
@Tapchicoma no I'd say none of them do... It is easy to reproduce in any non-Kotlin project. Here are a couple of examples:
* [This project is plain Java](https://github.com/DanySK/jirf/tree/bump-ktlint-to-10.0.0)
* [This project uses Xtend](https://github.com/DanySK/listset/tree/bump-ktlint-to-10.0.0)

**Comment by Tapchicoma** [comment]
Found the issue - wrong import slipped into task on this line: https://github.com/JLLeitschuh/ktlint-gradle/blob/83e51ee716dc41781106555eb5f0f53d3dedda80/plugin/src/main/kotlin/org/jlleitschuh/gradle/ktlint/tasks/GenerateReportsTask.kt#L20

Will fix for the next release, thank you for reporting it :+1:

**Comment by DanySK** [comment]
You are welcome, looking forward to the new release!

**Comment by DanySK** [comment]
@Tapchicoma, any ETA for the next release?
This issue, although solved, is now blocking Gradle updates for me in several projects.

Thanks!
