### ISSUE TITLE
ktlint 0.47.x breaks plugin

### ISSUE THREAD

**Issue by chrisjenx** [JLLeitschuh/ktlint-gradle#607]
The major version bump unfortunately breaks the plugin :(

```
Caused by: java.lang.NoClassDefFoundError: com/pinterest/ktlint/core/KtLint$Params
        at org.jlleitschuh.gradle.ktlint.worker.KtLintWorkAction.execute(KtLintWorkAction.kt:52)
        at org.gradle.workers.internal.DefaultWorkerServer.execute(DefaultWorkerServer.java:63)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:49)
        at org.gradle.workers.internal.AbstractClassLoaderWorker$1.create(AbstractClassLoaderWorker.java:43)

```

**Comment by eboudrant** [comment]
Related to https://github.com/pinterest/ktlint/issues/1532

**Comment by JLLeitschuh** [comment]
https://github.com/JLLeitschuh/ktlint-gradle/releases/tag/v11.1.0
