### ISSUE TITLE
java.lang.NoClassDefFoundError: com/android/build/api/dsl/CommonExtension

### ISSUE THREAD

**Issue by Jadyli** [JLLeitschuh/ktlint-gradle#608]
ktlint gradle version: 11.0.0
agp version: 7.2.2
gradle version: gradle-7.5.1-bin

After removing ktlint, the project can run sync and build normally.

java.lang.NoClassDefFoundError: com/android/build/api/dsl/CommonExtension
	at org.jlleitschuh.gradle.ktlint.android.AndroidPluginsApplierKt$androidPluginConfigureAction$1.invoke(AndroidPluginsApplier.kt:67)
	at org.jlleitschuh.gradle.ktlint.android.AndroidPluginsApplierKt$androidPluginConfigureAction$1.invoke(AndroidPluginsApplier.kt:66)
	at org.jlleitschuh.gradle.ktlint.android.AndroidPluginsApplierKt$applyKtLintToAndroid$1.invoke$lambda-0(AndroidPluginsApplier.kt:29)
	at org.gradle.configuration.internal.DefaultUserCodeApplicationContext$CurrentApplication$1.execute(DefaultUserCodeApplicationContext.java:123)

**Comment by dfavaro** [comment]
Same here. Trying to integrate `ktlint gradle` in [this template](https://github.com/android/architecture-templates/tree/multimodule) following the doc, into the root build.gradle. Getting the same error. Would appreciate some help.

**Comment by Sevastyan** [comment]
Having the same issue with version `12.1.1` even.

`buildSrc/settings.gradle.kts`:

```
dependencyResolutionManagement {
    versionCatalogs {
        create("libs") {
            from(files("../gradle/libs.versions.toml"))
        }
    }
}
```

`buildSrc/build.gradle.kts`:

```
plugins {
    `kotlin-dsl`
}

repositories {
    gradlePluginPortal()
    google()
    mavenCentral()
}


dependencies {
    implementation(libs.gradlePlugin.ktlint)
}
```

`buildSrc/src/main/kotlin/...gradle.kts`:

```
plugins {
    id("org.jlleitschuh.gradle.ktlint")
}
```

`libs.versions.toml`:

```
...
[libraries]
gradlePlugin-ktlint = "org.jlleitschuh.gradle:ktlint-gradle:12.1.1"
...
```
