### ISSUE TITLE
`disabledRules` is deprecated, what is the alternative?

### ISSUE THREAD

**Issue by thedroiddiv** [JLLeitschuh/ktlint-gradle#671]
## Issue
When I try to run `ktlintFormat` with `disabledRules` set in my configuration, the task fails. 
Removing the `disabledRules` solves the issue, but what is its replacement?

warning: 'disabledRules: SetProperty<String>' is deprecated. not supported with ktlint 0.48+

## Stacktrace

```bash
BUILD FAILED in 814ms
15 actionable tasks: 1 executed, 14 up-to-date
➜  karya-android-client git:(main) ✗ ./gradlew ktlintFormat --stacktrace

> Task :karya:ktlintMainSourceSetFormat FAILED
....


FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':karya:ktlintMainSourceSetFormat'.
> A failure occurred while executing org.jlleitschuh.gradle.ktlint.worker.ConsoleReportWorkAction
   > KtLint found code style violations. Please see the following reports:
     - /Users/divyansh/Karya/karya-android-client/karya/build/reports/ktlint/ktlintMainSourceSetFormat/ktlintMainSourceSetFormat.txt

* Try:
> Run with --info or --debug option to get more log output.
> Run with --scan to get full insights.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':karya:ktlintMainSourceSetFormat'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.lambda$executeIfValid$1(ExecuteActionsTaskExecuter.java:149)
        at org.gradle.internal.Try$Failure.ifSuccessfulOrElse(Try.java:282)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeIfValid(ExecuteActionsTaskExecuter.java:147)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:135)
        at org.gradle.api.internal.tasks.execution.FinalizePropertiesTaskExecuter.execute(FinalizePropertiesTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.ResolveTaskExecutionModeExecuter.execute(ResolveTaskExecutionModeExecuter.java:51)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:57)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:74)
        at org.gradle.api.internal.tasks.execution.CatchExceptionTaskExecuter.execute(CatchExceptionTaskExecuter.java:36)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.executeTask(EventFiringTaskExecuter.java:77)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:55)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter$1.call(EventFiringTaskExecuter.java:52)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:204)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$CallableBuildOperationWorker.execute(DefaultBuildOperationRunner.java:199)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:66)
        at org.gradle.internal.operations.DefaultBuildOperationRunner$2.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:157)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.execute(DefaultBuildOperationRunner.java:59)
        at org.gradle.internal.operations.DefaultBuildOperationRunner.call(DefaultBuildOperationRunner.java:53)
        at org.gradle.internal.operations.DefaultBuildOperationExecutor.call(DefaultBuildOperationExecutor.java:73)
        at org.gradle.api.internal.tasks.execution.EventFiringTaskExecuter.execute(EventFiringTaskExecuter.java:52)
        at org.gradle.execution.plan.LocalTaskNodeExecutor.execute(LocalTaskNodeExecutor.java:42)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:338)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$InvokeNodeExecutorsAction.execute(DefaultTaskExecutionGraph.java:325)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:318)
        at org.gradle.execution.taskgraph.DefaultTaskExecutionGraph$BuildOperationAwareExecutionAction.execute(DefaultTaskExecutionGraph.java:304)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.execute(DefaultPlanExecutor.java:463)
        at org.gradle.execution.plan.DefaultPlanExecutor$ExecutorWorker.run(DefaultPlanExecutor.java:380)
        at org.gradle.execution.plan.DefaultPlanExecutor.process(DefaultPlanExecutor.java:116)
        at 
        ...

**Comment by wakingrufus** [comment]
The replacement is using .editorconfig per the ktlint [docs](https://pinterest.github.io/ktlint/0.49.1/faq/#how-do-i-globally-disable-a-rule)

**Comment by divyanshdxn** [comment]
What should I do, if I just want to disable no-widlcard-imports?

**Comment by LiberaTeMetuMortis** [comment]
> The replacement is using .editorconfig per the ktlint [docs](https://pinterest.github.io/ktlint/0.49.1/faq/#how-do-i-globally-disable-a-rule)

Are there any example .editorconfig files?

**Comment by khkramer** [comment]
The plugin seems to ignore .editorconfig on my system.

**Comment by LiberaTeMetuMortis** [comment]
> The plugin seems to ignore .editorconfig on my system.

Do you configure the plugin (you must)

Here is an [example of configuration] (https://github.com/LiberaTeMetuMortis/KotlinSpigotPluginTemplate/blob/master/project/build.gradle.kts)

If you want to be able to edit preferences in .editorconfig you must configure it even if you won't change anything

**Comment by Azamat989** [comment]
@LiberaTeMetuMortis 

I added configuration task like:

```
ktlint {
    version = "0.49.1"
}
```

but the plugin continues to ignore my .editorconfig

**Comment by LiberaTeMetuMortis** [comment]
> @LiberaTeMetuMortis
> 
> I added configuration task like:
> 
> ```
> ktlint {
>     version = "0.49.1"
> }
> ```
> 
> but the plugin continues to ignore my .editorconfig

It can be because of your .editorconfig's location, have no other idea than that.

**Comment by Azamat989** [comment]
> > @LiberaTeMetuMortis
> > I added configuration task like:
> > ```
> > ktlint {
> >     version = "0.49.1"
> > }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > but the plugin continues to ignore my .editorconfig
> 
> It can be because of your .editorconfig's location, have no other idea than that.

I have it in my project root directory, like: /Users/me/StudioProjects/project-name/.editorconfig

**Comment by idunnololz** [comment]
On 11.5.0 of the plugin I am able to get this to work. I had to set the ktlin version explicitly on all subprojects like so:
```
subprojects {
  apply(plugin = "org.jlleitschuh.gradle.ktlint")

  configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
    version.set("0.50.0")
    android.set(true)
  }
}

configure<org.jlleitschuh.gradle.ktlint.KtlintExtension> {
  version.set("0.50.0")
}
```

**Comment by JLLeitschuh** [comment]
As with almost all Gradle plugins, plugins are applied to only the projects they are applied to, and the configuration of the plugin only occurs when the plugin is explicitly configured.

@idunnololz you could also just use `allprojects` to apply a given configuration to all projects

**Comment by wakingrufus** [comment]
Thank you @idunnololz for providing the answer
