### ISSUE TITLE
gradle 7.6 fails to apply plugin with hint to minimal Gradle version 6.8

### ISSUE THREAD

**Issue by magrimuc** [JLLeitschuh/ktlint-gradle#678]
my build.gradle calls in line 44:
plugins {
    // ktlint Plugin
    id "org.jlleitschuh.gradle.ktlint" version "11.4.0"
...
java version openjdk 11.0.19
gradle-wrapper.properties: distributionUrl=https\://services.gradle.org/distributions/gradle-7.6-bin.zip
...
stacktrace:
`kotlin/element-android$ gradle build --stacktrace
Parallel execution with configuration on demand is an incubating feature.

FAILURE: Build failed with an exception.

* Where:
Build file '/home/name/Dokumente/kotlin/element-android/build.gradle' line: 44

* What went wrong:
An exception occurred applying plugin request [id: 'org.jlleitschuh.gradle.ktlint', version: '11.4.0']
> Failed to apply plugin [class 'org.jlleitschuh.gradle.ktlint.KtlintBasePlugin']
   > Current version of plugin supports minimal Gradle version: 6.8

* Try:
Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Exception is:
org.gradle.api.plugins.InvalidPluginException: An exception occurred applying plugin request [id: 'org.jlleitschuh.gradle.ktlint', version: '11.4.0']
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.exceptionOccurred(DefaultPluginRequestApplicator.java:247)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugin(DefaultPluginRequestApplicator.java:229)
        at org.gradle.plugin.use.internal.DefaultPluginRequestApplicator.applyPlugins(DefaultPluginRequestApplicator.java:148)
        at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:179)
        at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:61)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:336)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor$RunnableBuildOperationWorker.execute(DefaultBuildOperationExecutor.java:328)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.execute(DefaultBuildOperationExecutor.java:199)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:110)
        at org.gradle.configuration.BuildOperationScriptPlugin.apply(BuildOperationScriptPlugin.java:58)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:41)
        at org.gradle.configuration.project.BuildScriptProcessor.execute(BuildScriptProcessor.java:26)
        at org.gradle.configuration.project.ConfigureActionsProjectEvaluator.evaluate(ConfigureActionsProjectEvaluator.java:34)
`

**Comment by magrimuc** [comment]
sry

**Comment by wakingrufus** [comment]
Looks like you ran with `gradle` instead of `./gradlew` could that be the issue?

**Comment by magrimuc** [comment]
yes. running ".\gradlew build" leads to different hints to solve.
That costs other effort of hopefully the right kind.
Thank you so much for your help!
